### ISSUE TITLE
it cannot be exported to Wwise,If Actor Mixer is selected for Object Type,

### ISSUE THREAD

**Issue by ronglizhou** [audiokinetic/ReaWwise#2] opened 2022-12-28 09:16 UTC
When exporting, it will prompted:Actor Mixer is not a known object type.

The Import Summary show that Actor Mixer means Actor-Mixer Hierarchy? So how to use the Actor Mixer Object Type?
![error](https://user-images.githubusercontent.com/46864603/209791572-089d171b-8835-4597-bd2a-34bea6325287.jpg)
![ReaWwise Import Summary](https://user-images.githubusercontent.com/46864603/209791578-d0e22b4c-4e35-4419-9efa-2a15ce5f4c7d.jpg)
![ReaWwise](https://user-images.githubusercontent.com/46864603/209791583-3842e366-88ee-488d-8050-fc382fce3719.jpg)

**Comment by ak-acosta** [comment] 2023-01-06 14:44
Hello @ronglizhou,

Thank you for the detailed report. 

What version of ReaWwise are you using? 

I'm asking this because there was a bug related to Actor-Mixer importing in v1.0.3 and below that was fixed in v1.0.4.

You can see the change here:

https://github.com/audiokinetic/ReaWwise/commit/6397e72977b9315e06b91fd2cb0d87958b2dc92c#diff-2f1bac65b8dc24d84d8a410175ba33bafed202d86d2dda4535ae107eba9460beR73

Let me know if you are using v1.0.4 and still encounter this issue.

Andrew

**Comment by ronglizhou** [comment] 2023-01-09 08:04
ReaWwise :v1.0.4
Reaper :v6.73
Wwise :2022.1.1.8100
Whatever I select ,When click Transfer to Wwise ,it will show this
![image](https://user-images.githubusercontent.com/46864603/211262400-d39d5df7-f848-4377-8212-4cc510dbfff1.png)

ReaWwise :v1.0.1
Reaper :v6.73
Wwise :2022.1.1.8100
If Actor Mixer is selected for Object Type ,when click Transfer to Wwise ,it will show this
![image](https://user-images.githubusercontent.com/46864603/211262817-e9ab4460-63e1-4e73-bbf6-f8b07b3fb0c2.png)

**Comment by ak-acosta** [comment] 2023-01-09 19:15
Hello @ronglizhou,

The issue you're experiencing with v1.0.4 is usually caused by problems with the render that occurs right before ReaWwise does the transfer to Wwise. 

Would you be able to send the latest log file? It would be located at %appdata%\ReaWwise\Logs.

Andrew

**Comment by ronglizhou** [comment] 2023-01-10 01:23
I have sent the log file to your email, please check

**Comment by ak-acosta** [comment] 2023-01-10 18:31
Hello @ronglizhou,

I looked at the log you sent me. There isn't enough in there to tell me what went wrong. I have created a new build of ReaWwise with extra logging. I've attached it to this comment.

Can you try it and then email me the latest log file? The extra logging that I added should help me understand why you keep getting errors.

[reaper_reawwise.zip](https://github.com/audiokinetic/ReaWwise/files/10385743/reaper_reawwise.zip)

You will need to manually copy the DLL to your UserPlugins directory and then restart REAPER.

Andrew

**Comment by ronglizhou** [comment] 2023-01-11 01:40
I have used the DLL, rendered Actor-Mixer and Blend Container to Wwise by using ReaWwise v1.0.1 and v1.0.4

[Log_2023-01-11.txt](https://github.com/audiokinetic/ReaWwise/files/10388073/Log_2023-01-11.txt)

All these operation will show this
![image](https://user-images.githubusercontent.com/46864603/211697179-0e72e978-dbda-472b-9c8e-595151b4af34.png)

**Comment by ak-acosta** [comment] 2023-01-11 17:40
Hello @ronglizhou,

Looks like ReaWwise has detected that no files where rendered after it triggered a render in REAPER. 

Can you confirm that the render in REAPER is successful? This render happens after you click the "Transfer to Wwise" button.

It is possible that there is a bug in the algorithm that detects that no files have been rendered. I have produced a new build for you that skips this check. I recommend that you backup your wwise and reaper project before using this version of ReaWwise since it hasn't been tested thoroughly. 

If the import succeeds using this new build, please validate that the correct files where imported into wwise.

If you encounter other issues, just send me the latest log file and we'll take it from there.

Andrew

[reaper_reawwise.zip](https://github.com/audiokinetic/ReaWwise/files/10394709/reaper_reawwise.zip)

**Comment by ronglizhou** [comment] 2023-01-12 01:49
The problem have been solved. Thanks.

By using the new DLL , ReaWwise v1.0.1 can "Transfer to Wwise" succesfully.

And the ReaWwise v1.0.4 is functional. The problem is that my Reaper project uses paths containing Chinese characters, so the rendered files can not be found and imported into Wwise

![image](https://user-images.githubusercontent.com/46864603/211959128-102db1ad-78b6-4408-ad00-c20677ce58f7.png)

**Comment by ak-acosta** [comment] 2023-01-12 14:53
Hello @ronglizhou,

I will investigate why the import doesn't work when using Chinese characters in your file paths.

In the meantime, if it's not to much of a problem, you can try working with file paths that do not contain those characters.

I will get back to you soon.

Andrew

**Comment by ak-acosta** [comment] 2023-01-13 15:06
Hello @ronglizhou,

We will be adding support for non English characters sets in the next version of ReaWwise. 

Andrew

**Comment by ak-acosta** [comment] 2023-07-21 18:34
This is fixed in ReaWwise 1.0.5 with the added support for Chineese characters.

**Closed as completed** 2023-07-21 18:35 UTC
